name: Build lxml wheel

on:
  push: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2022
        python:
          - "3.15-dev"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          repository: lxml/lxml
          ref: lxml-6.1.1
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install python deps
        run: |
          pip install -U build wheel cython==3.3.0a1
      - name: Build lxml wheel
        shell: bash
        env:
          # https://github.com/lxml/lxml/blob/lxml-6.1.1/pyproject.toml
          ZLIB_VERSION: '1.3.2'
          LIBICONV_VERSION: '1.18'
          LIBXML2_VERSION: '2.14.6'
          LIBXSLT_VERSION: '1.1.43'
          STATIC_DEPS: true
          WITH_CYTHON: true
        run: |
          export MULTICORE=$(nproc)
          if [[ $(uname) == "Linux" ]]; then
            export CFLAGS="-O3 -g1 -pipe -fPIC -flto"
            export LDFLAGS="-fPIC -flto"
          fi
          python -m build --wheel
      - name: Validate built wheel
        shell: bash
        run: |
          pip install ./dist/*.whl
          python -c 'import lxml.etree;[print(f"lxml.etree.{k} == {getattr(lxml.etree,k)}") for k in ["__version__","LIBXML_VERSION","LIBXSLT_VERSION"]]'
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./dist/*.whl
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: mkdir dist
      - uses: actions/download-artifact@v8
        with:
          skip-decompress: true
          merge-multiple: true
          path: ./dist
      - name: Release
        uses: ncipollo/release-action@36e78ab6296394ce36f72f6488e68c2353b50514
        with:
          artifacts: dist/*.whl
