name: Build lxml wheel

on:
  push: {}

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          repository: lxml/lxml
          ref: 2a67034bc21150e9cc14500f65c41fa4e9d51c9b
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14-dev"
      - name: Install python deps
        run: |
          pip install -U build wheel cython
      - name: Build lxml wheel
        shell: bash
        run: |
          export LIBXML2_VERSION=2.14.4
          export LIBXSLT_VERSION=1.1.43
          export STATIC_DEPS=true
          export WITH_CYTHON=true
          export MULTICORE=$(nproc)
          if [[ $(uname) == "Linux" ]]; then
            export CFLAGS="-O3 -g1 -pipe -fPIC -flto"
            export LDFLAGS="-fPIC -flto"
          fi
          python -m build --wheel
      - name: Validate built wheel
        shell: bash
        run: |
          pip install ./dist/lxml-*.whl
          python -c 'import lxml.etree;[print(f"lxml.etree.{k} == {getattr(lxml.etree,k)}") for k in ["__version__","LIBXML_VERSION","LIBXSLT_VERSION"]]'
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ./dist/lxml-*.whl
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: mkdir dist
      - uses: actions/download-artifact@v4
        with:
          path: ./dist
      - name: Release
        uses: ncipollo/release-action@36e78ab6296394ce36f72f6488e68c2353b50514
        with:
          artifacts: dist/**/*.whl
