name: Build pycryptodome wheel

on:
  push: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - "3.14t"
          - "3.15-dev"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Build wheel
        shell: bash
        run: |
          python -m pip wheel -w dist git+https://github.com/Legrandin/pycryptodome@d12264940c40417915fb85acb8c787ad9da58969
      - uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ./dist/*.whl
  deploy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: mkdir dist
      - uses: actions/download-artifact@v8
        with:
          skip-decompress: true
          merge-multiple: true
          path: ./dist
      - name: Release
        uses: ncipollo/release-action@36e78ab6296394ce36f72f6488e68c2353b50514
        with:
          artifacts: dist/*.whl
